BJM.DVDCentral.UI/Controllers/OrderController.cs
using BJM.DVDCentral.UI.Models;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace BJM.DVDCentral.UI.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Title = "List of Orders";
            return View(OrderManager.Load());
        }
        public IActionResult Details(int id)
        {
            ViewBag.Title = "Details for this Order";
            var item = OrderManager.LoadById(id);
            return View(item);
        }
        public IActionResult Create()
        {
            ViewBag.Title = "Create an Order";
            if (Authenticate.IsAuthenticated(HttpContext))
                return View();
            else
                return RedirectToAction("Login", "User", new { returnUrl = UriHelper.GetDisplayUrl(HttpContext.Request)});
        }
        [HttpPost]
        public IActionResult Create(Order director, bool rollback = false)
        {
            try
            {
                int result = OrderManager.Insert(director, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Title = "Create an Order";
                ViewBag.Error = ex.Message;
                throw;
            }
        }
        public IActionResult Edit(int id)
        {
            ViewBag.Title = "Edit an Order";
            if (Authenticate.IsAuthenticated(HttpContext))
                return View(OrderManager.LoadById(id));
            else
                return RedirectToAction("Login", "User", new { returnUrl = UriHelper.GetDisplayUrl(HttpContext.Request) });

        }
        [HttpPost]
        public IActionResult Edit(int id, Order director, bool rollback = false)
        {
            try
            {
                int result = OrderManager.Update(director, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Title = "Edit an Order";
                ViewBag.Error = ex.Message;
                return View(director);
            }
        }
        public IActionResult Delete(int id)
        {
            ViewBag.Title = "Delete an Order";
            return View(OrderManager.LoadById(id));
        }
        [HttpPost]
        public IActionResult Delete(int id, Order director, bool rollback = false)
        {
            try
            {
                ViewBag.Title = "Delete an Order";
                int result = OrderManager.Delete(id, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(director);
            }
        }
    }
}

BJM.DVDCentral.UI/Controllers/OrderItemController.cs
using BJM.DVDCentral.BL.Models;
using Microsoft.AspNetCore.Mvc;
using System.Xml.Linq;

namespace BJM.DVDCentral.UI.Controllers
{
    public class OrderItemController : Controller
    {
        public IActionResult Index()
        {
            return View(OrderItemManager.Load());
        }
        [HttpPost]
        public IActionResult Remove(int id)
        {
            try
            {
                OrderItem orderItem = OrderItemManager.LoadById(id);

                if (orderItem != null)
                {
                    OrderItemManager.Delete(id);
                    return RedirectToAction("Edit", "Order", new { id = orderItem.OrderId });
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception ex)
            {
                throw new Exception();
            }
        }
    }
}

BJM.DVDCentral.UI/Views/Order/Create.cshtml
@model BJM.DVDCentral.BL.Models.Order

<hr />
<div class="row m-2">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <input asp-for="CustomerId" class="form-control" />
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipDate" class="control-label"></label>
                <input asp-for="ShipDate" class="form-control" />
                <span asp-validation-for="ShipDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BJM.DVDCentral.UI/Views/Order/Delete.cshtml
@model BJM.DVDCentral.BL.Models.Order


<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShipDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShipDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <div>
            <partial name="_OrderPartial" model="Model.Items" />
        </div>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BJM.DVDCentral.UI/Views/Order/Details.cshtml
@model BJM.DVDCentral.BL.Models.Order


<div>
    <hr />
    <dl class="row m-2">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShipDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShipDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd> 
        
        <div>
            <partial name="_OrderPartial" for="Items" />
        </div>
        

    </dl>
</div>
<div m-2>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

BJM.DVDCentral.UI/Views/Order/Edit.cshtml
@model BJM.DVDCentral.BL.Models.Order


<hr />
<div class="row m-2">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ShipDate" class="control-label"></label>
                <input asp-for="ShipDate" class="form-control" />
                <span asp-validation-for="ShipDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group m-2">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Movie Title</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>@* @item.Movie.Title *@</td>
                <td>@item.Quantity</td>
                <td>@item.Cost</td>
                <td>
                    <form asp-controller="OrderItem" asp-action="Remove" method="post">
                        <input type="hidden" asp-for="Id" value="@item.Id" />
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="m-2">
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BJM.DVDCentral.UI/Views/Order/Index.cshtml
@model IEnumerable<BJM.DVDCentral.BL.Models.Order>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table m-2" id="orderItemsTable">
    <thead>
        <tr>
            <th>
                Order Number
            </th>

            <th>
                @Html.DisplayNameFor(model => model.ShipDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShipDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id  }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

@section Scripts {
<script>
    $(document).ready(function () {
        $('#orderItemsTable').DataTable({
            "lengthMenu": [[5, 10, 25, 30, -1], [5, 10, 25, 30, "All"]]

        });
    });
</script>
}