BJM.DVDCentral.UI/Controllers/GenreController.cs
using BJM.DVDCentral.UI.Models;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;

namespace BJM.DVDCentral.UI.Controllers
{
    #region "Pre-Web-API"
    public class GenreController : Controller
    {
        public IActionResult Index()
        {
            return View(GenreManager.Load());
        }
        public IActionResult Details(int id)
        {
            return View(GenreManager.LoadById(id));
        }
        public IActionResult Create()
        {
            if (Authenticate.IsAuthenticated(HttpContext))
                return View();
            else
                return RedirectToAction("Login", "User", new { returnUrl = UriHelper.GetDisplayUrl(HttpContext.Request) });
        }
        [HttpPost]
        public IActionResult Create(Genre genre, bool rollback = false)
        {
            try
            {
                int result = GenreManager.Insert(genre, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {

                throw;
            }
        }
        public IActionResult Edit(int id)
        {
            if (Authenticate.IsAuthenticated(HttpContext))
                return View(GenreManager.LoadById(id));
            else
                return RedirectToAction("Login", "User", new { returnUrl = UriHelper.GetDisplayUrl(HttpContext.Request) });   
        }
        [HttpPost]
        public IActionResult Edit(int id, Genre genre, bool rollback = false)
        {
            try
            {
                int result = GenreManager.Update(genre, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(genre);
            }
        }
        public IActionResult Delete(int id)
        {
            return View(GenreManager.LoadById(id));
        }
        [HttpPost]
        public IActionResult Delete(int id, Genre genre, bool rollback = false)
        {
            try
            {
                int result = GenreManager.Delete(id, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(genre);
            }
        }
        #endregion
        #region "Web-API"


        private static HttpClient InitializeClient()
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:7264/api/");
            return client;
        }

        public IActionResult Get()
        {
            ViewBag.Title = "List of all genres";
            HttpClient client = InitializeClient();

            HttpResponseMessage response = client.GetAsync("Genres").Result;

            string result = response.Content.ReadAsStringAsync().Result;

            dynamic items = (JArray)JsonConvert.DeserializeObject(result);
            List<Genre> genres = items.ToObject<List<Genre>>();
            return View(nameof(Index), genres);
        }

        public IActionResult GetOne(int id)
        {
            ViewBag.Title = "Genre Details";
            HttpClient client = InitializeClient();

            HttpResponseMessage response = client.GetAsync($"Genres/{id}").Result;

            string result = response.Content.ReadAsStringAsync().Result;
            dynamic item = JsonConvert.DeserializeObject(result);
            Genre genre = item.ToObject<Genre>();

            return View(nameof(Details), genre);
        }

        public IActionResult Insert()
        {
            ViewBag.Title = "Create a Genre";
            return View(nameof(Create));
        }

        [HttpPost]
        public IActionResult Insert(Genre genre)
        {
            try
            {
                HttpClient client = InitializeClient();
                string serializedObject = JsonConvert.SerializeObject(genre);
                var content = new StringContent(serializedObject);
                content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");

                HttpResponseMessage response = client.PostAsync("Genres", content).Result;
                return RedirectToAction(nameof(Get));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(nameof(Create), genre);
            }
        }

        public IActionResult Update(int id)
        {
            ViewBag.Title = "Update Genre";
            HttpClient client = InitializeClient();

            HttpResponseMessage response = client.GetAsync($"Genres/{id}").Result;

            string result = response.Content.ReadAsStringAsync().Result;
            dynamic item = JsonConvert.DeserializeObject(result);
            Genre genre = item.ToObject<Genre>();

            return View(nameof(Edit), genre);
        }

        [HttpPost]
        public IActionResult Update(int id, Genre genre)
        {
            try
            {
                HttpClient client = InitializeClient();
                string serializedObject = JsonConvert.SerializeObject(genre);
                var content = new StringContent(serializedObject);
                content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");

                HttpResponseMessage response = client.PutAsync($"Genres/{id}", content).Result;
                return RedirectToAction(nameof(Get));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(nameof(Edit), genre);
            }
        }

        public IActionResult Remove(int id)
        {
            HttpClient client = InitializeClient();

            HttpResponseMessage response = client.GetAsync($"Genres/{id}").Result;

            string result = response.Content.ReadAsStringAsync().Result;
            dynamic item = JsonConvert.DeserializeObject(result);
            Genre genre = item.ToObject<Genre>();

            return View(nameof(Delete), genre);
        }

        [HttpPost]
        public IActionResult Remove(int id, Genre genre)
        {
            try
            {
                HttpClient client = InitializeClient();
                HttpResponseMessage response = client.DeleteAsync($"Genres/{id}").Result;
                return RedirectToAction(nameof(Get));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(nameof(Delete), genre);
            }
        }


        #endregion
    }
}

BJM.DVDCentral.UI/Controllers/OrderController.cs
using BJM.DVDCentral.UI.Models;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace BJM.DVDCentral.UI.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Title = "List of Orders";
            return View(OrderManager.Load());
        }
        public IActionResult Details(int id)
        {
            ViewBag.Title = "Details for this Order";
            var item = OrderManager.LoadById(id);
            return View(item);
        }
        public IActionResult Create()
        {
            ViewBag.Title = "Create an Order";
            if (Authenticate.IsAuthenticated(HttpContext))
                return View();
            else
                return RedirectToAction("Login", "User", new { returnUrl = UriHelper.GetDisplayUrl(HttpContext.Request)});
        }
        [HttpPost]
        public IActionResult Create(Order director, bool rollback = false)
        {
            try
            {
                int result = OrderManager.Insert(director, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Title = "Create an Order";
                ViewBag.Error = ex.Message;
                throw;
            }
        }
        public IActionResult Edit(int id)
        {
            ViewBag.Title = "Edit an Order";
            if (Authenticate.IsAuthenticated(HttpContext))
                return View(OrderManager.LoadById(id));
            else
                return RedirectToAction("Login", "User", new { returnUrl = UriHelper.GetDisplayUrl(HttpContext.Request) });

        }
        [HttpPost]
        public IActionResult Edit(int id, Order director, bool rollback = false)
        {
            try
            {
                int result = OrderManager.Update(director, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Title = "Edit an Order";
                ViewBag.Error = ex.Message;
                return View(director);
            }
        }
        public IActionResult Delete(int id)
        {
            ViewBag.Title = "Delete an Order";
            return View(OrderManager.LoadById(id));
        }
        [HttpPost]
        public IActionResult Delete(int id, Order director, bool rollback = false)
        {
            try
            {
                ViewBag.Title = "Delete an Order";
                int result = OrderManager.Delete(id, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(director);
            }
        }
    }
}

BJM.DVDCentral.UI/Controllers/RatingController.cs
using Microsoft.AspNetCore.Mvc;

namespace BJM.DVDCentral.UI.Controllers
{
    public class RatingController : Controller
    {
        public IActionResult Index()
        {
            return View(RatingManager.Load());
        }
        public IActionResult Details(int id)
        {
            return View(RatingManager.LoadById(id));
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Rating rating, bool rollback = false)
        {
            try
            {
                int result = RatingManager.Insert(rating, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {

                throw;
            }
        }
        public IActionResult Edit(int id)
        {
            return View(RatingManager.LoadById(id));
        }
        [HttpPost]
        public IActionResult Edit(int id, Rating rating, bool rollback = false)
        {
            try
            {
                int result = RatingManager.Update(rating, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(rating);
            }
        }
        public IActionResult Delete(int id)
        {
            return View(RatingManager.LoadById(id));
        }
        [HttpPost]
        public IActionResult Delete(int id, Rating rating, bool rollback = false)
        {
            try
            {
                int result = RatingManager.Delete(id, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(rating);
            }
        }
    }
}

BJM.DVDCentral.UI/Controllers/UserController.cs
using BJM.DVDCentral.UI.Extentions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BJM.DVDCentral.UI.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        //public IActionResult Seed()
        //{
        //    UserManager.Seed();
        //    return View();
        //}
        private void SetUser(User user)
        {
            HttpContext.Session.SetObject("user", user);
            if (user != null)
            {
                HttpContext.Session.SetObject("fullname", "Welcome " + user.FullName);
            }
            else
            {
                HttpContext.Session.SetObject("fullname", string.Empty);
            }
        }

        public IActionResult Logout()
        {
            ViewBag.Title = "Logout";
            SetUser(null);
            return View();
        }
        public IActionResult Login(string returnUrl)
        {
            TempData["returnUrl"] = returnUrl;
            return View();
        }
        [HttpPost]
        public IActionResult Login(User user)
        {
            try
            {
                bool result = UserManager.Login(user);
                SetUser(user);
                if (TempData["returnUrl"] != null)
                return Redirect(TempData["returnUrl"]?.ToString());
                else
                return RedirectToAction(nameof(Index), "Movie");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(user);
            }
        }
        public IActionResult Edit(int userId)
        {
            User user = UserManager.LoadById(userId);
            return View(user);
        }

        [HttpPost]
        public IActionResult Edit(User user, bool rollback = false)
        {
            try
            {
                int result = UserManager.Update(user, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(user);
            }
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(User user)
        {
            UserManager.Insert(user);
            return RedirectToAction(nameof(Index));
        }
    }
}

BJM.DVDCentral.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BJM.DVDCentral.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BJM.DVDCentral.UI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">DVDCentral</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Rating" asp-action="Index">Rating</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Director" asp-action="Index">Director</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Movie" asp-action="Index">Movie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Genre" asp-action="Index">Genre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                        @{
                            BJM.DVDCentral.BL.UserManager.Seed();
                            HttpContext httpContext = Context.Request.HttpContext;
                            if (Authenticate.IsAuthenticated(httpContext))
                            {
                                <ul class="navbar-nav ms-auto">
                                    <li class="nav-item">
                                        @{
                                            
                                            var fullname = HttpContextAccessor.HttpContext?.Session.GetString("fullname");
                                            if (fullname != null) fullname = fullname.Replace("\"", "");
                                        }
                                        <a class="nav-link text-light">@fullname</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                                        <!-- <span class="nav-link text-light">Welcome</span> -->
                                    </li>
                                </ul>
                            }
                            else
                            {
                                <li class="nav-item ms-auto">
                                    <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                                </li>
                            }
                            
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 sidebar rounded-top">
                <div class="header rounded-top p-1">
                    <h4>Movies</h4>
                </div>
                <div>
                    @await Component.InvokeAsync("Sidebar")
                </div>
                <div class="header p-1">
                    <h4>Shopping Cart</h4>
                </div>
                <div>
                    @await Component.InvokeAsync("ShoppingCartComponent")
                </div>
            </div>
            <div id="overlay" onclick="off()">
                <div class="imageproplarge">
                    <img class="imageproplarge" id="output" />
                </div>
            </div>
            <div class="col-md-9 main body-content rounded-top">
                <div class="header rounded-top p-1">
                    <h4>@ViewBag.Title</h4>
                </div>
                <main role="main" class="pb-3">
                    <div class="text-danger ms-2">
                        <h4>@ViewBag.Error</h4>
                    </div>
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BJM.DVDCentral.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<script type="text/javascript">
    function off() {
        console.log('Off')
        document.getElementById("overlay").style.display = "none";
    }
    function on(picture) {
        console.log('On')
        document.getElementById("overlay").style.display = "block";
        document.getElementById("output").src = picture;
    }
</script>
<script type="text/javascript">
    function AddToCart(id) {
        $.get("/ShoppingCart/Add/" + id, function (data) {
            var cartcount = parseInt($("#cartcount").val()) + 1;
            $("#cartcount").val(cartcount);
            $("#cartcountdisp").text(cartcount + " items");
            console.log(cartcount + " items");
        });
    }
</script>

BJM.DVDCentral.UI/Views/Shared/_OrderPartial.cshtml
@model IEnumerable<BJM.DVDCentral.BL.Models.OrderItem>

@if (Model != null && Model.Any())
{
    <table id="orderItemsTable" class="table">
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Movie ID</th>
                <th>Quantity</th>
                <th>Cost</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @{
                var groupedItems = Model.GroupBy(item => item.MovieId);
            }
            @foreach (var group in groupedItems)
            {
                var totalQuantity = group.Sum(item => item.Quantity);
                var firstItem = group.First(); 

                <tr>
                    <td>@Html.DisplayFor(modelItem => firstItem.OrderId)</td>
                    <td>@Html.DisplayFor(modelItem => firstItem.MovieId)</td>
                    <td>@totalQuantity</td>
                    <td>@(firstItem.Cost.ToString("C"))</td>
                    <td>
                        @foreach (var orderItem in group)
                        {
                            <a asp-controller="Advisor" asp-action="Edit" asp-route-id="@orderItem.Id">Edit</a>
                            <a asp-controller="Advisor" asp-action="Details" asp-route-id="@orderItem.Id">Details</a>
                            <a asp-controller="Advisor" asp-action="Delete" asp-route-id="@orderItem.Id">Delete</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#orderItemsTable').DataTable({
                "lengthMenu": [[5, 10, 25, 30, -1], [5, 10, 25, 30, "All"]]
            });
        });
    </script>
}